import socket

UDP_IP = "192.168.0.23"
UDP_PORT = 5005

pesan = """IANACR INAFFGFNIR NAGAMIAICGG IIG IFI MMD MDIARMAI G D A INNIAINDMID ANIMCCR  ADFM ACG AN ADNDAACAGIAGFCDDG    RMINC    NDNNN FAIF MA DFAAAIAAAN MAMRNIF FCM ARARAM GNNRC AFIN ARRNANGFAMAANCARAMDM GMAAMIIINCNA AAD MINANIMRIAGNAMIFMAFRFIAM RRFDANMDGA AM  IG AMAMFRCNAIA RDANCAGAIAICINIGAA AADAADMGNFDG IFDD CAIMCGNA N ANMC IRANAANNC RMMIDDIADIAGM NDMAAIRGGAIFF RI MACMA F NIRANCNIADAFINCAN  ANIGDAMA RCAAAAA RCAGNGMAAADGMAACCDAAFM NRDAFNCRIARDMD   IFDNAAA I IAIARFNARN NGRADNIAAAFAICIDF CIIGFFIANNC   CFGGC MMGIIIANRN N INNANANAANNIIRDI MDA NDGNCNGN DA F GIDNIAAACM GARAMIGNM R ANFCCRAIFCIFRMNIRFIN DDCCARNMAN GAFA NNAFGAMINNAMIIN  A  CANMIRII CADCGNC  FDNAAGACICFMDM  AFI  DMAAADFIANI  RFAINCMMADAGGACIDAFIA CARIACNDACFCNANFG FIDA FNNIDC RIRRCNNDG DADIFIFFRFR IANNGAMNA  NAFINCAF NI AAGNG ICMCNGGGDIIANN  AI CC CADFCMDRM IA MCMIIADID ACGN FFGCDINIM INMMAAM FMDMFAM FNDFGFA  FMIDIMDMFIMCGA F NNMAANAAGNRMCFN N IM  FIINNDAF NIDCFMIIIIRDFADIN AFM MNAFMG FM   IRARCCDIDNAACRAIANNIC AC    ACGIDAGNANA IARARRAAAM RMI AMAAR MAMNADMNCNANRMANINNCGIDGAIAAICD AFIRF GMACA M GCRA G  IACCAAAAADAANACIGRDMN   FDIAGRAIDMIIDDAANA  ACFIFGAMI RINF CAG  AANICDIGDDINGRCIMF MNIM G GARMMAI D GICDNFAMINRAANA  GGAAFIIMGANAAINA NDA DAANAFDNAFNAI  IAID NCACANFINGDAAIIRN INCICAMN  GAG NG DRMNADD RIF ANCAC NR FFNDGFA A GNNM IFMIF  NNMGIG CFFAIANA AIAIRRFI FCDGGGIMGF N AAA AFMIGFDNAAFGAFA AAAGAANADAAIINMRINIFAGDCAF ANIIAARAICAAAAN  FFA NADGMG AAGDIIIRID AIRNA FAINRAAADGCIC NRGF CIFDMADAR DNIDNICN GCRCMNMR AAGN AF NI RN IA  FN RGRRDAFAIRAACIC AIDAF IR IICAD  ICRAADIANAIAACMIMDNCIMAFCMCI DMCCMR INRNGANDNNNAGDIFRFMF I NAAFA AGIAA IIR  NGAGDCNNNAIACAFDDCNFA MANIADAC  DIRA IDDA NN FGANCN I   RAM GCRA AADANAAINANIRG AD MNNRNIAICIAANC AG RIAA CFGIICANG AIF NIARRMF  NMIN AIIGNNN NDGN AAIMIAIFRIAMFAGDRANFM AGAMAAADG GMDI NM FGIMFNINGGG ANMAGMA F N MCGF AAGDAGAM CACNNNIAGDCFANNR NIRFANNAR NRCNAMFMNMAFRIMFI INNNACAFINAM DGDNFI N G ANDN  DAAMCARN ANG CIRDIRFIA NGIMCFFCAIDCGRDNI CM NII DGDND   IN AA FIACDANC II F MDM NIIDRACRIRMMIA  IACGCANCIIACNIC MRN IMNAAANA NA IIDIMNFRN
"""

print(f"Target IP \t\t: {UDP_IP}")
print(f"Target Port \t\t: {UDP_PORT}")
print(f"Pesan \t\t\t: {pesan}")

# Membuat Socket UDP
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) # UDP

# Mengirim pesan ke server
sock.sendto(pesan.encode(), (UDP_IP, UDP_PORT))                    